export const siteConfig = {
  name: "Miles Ni — AI Entrepreneur & Multi-Agent Architect",
  authorName: "Miles Ni",
  username: "milesnee",
  description:
    "Miles Ni (倪磊) — AI entrepreneur with 14 years of full-stack data experience. Building at the intersection of AI agents, quantitative trading, and mental wellness. Explore my projects, research, and open-source contributions.",
  url: "https://milesnee.github.io",
  links: {
    twitter: "https://x.com/MilesNee",
    github: "https://github.com/milesnee",
  },
  ogImage: "/og-image.png",
  iconIco: "/favicon.ico",
  logoIcon: "/logo.png",
  keywords: [
    "Miles Ni",
    "倪磊",
    "AI Entrepreneur",
    "AI Agent",
    "Multi-Agent Orchestration",
    "Quantitative Trading",
    "Crypto",
    "Data Engineering",
    "Data Governance",
    "MCP",
    "OpenClaw",
    "Python",
    "LLM",
    "老麦茶馆",
    "XiaoCheng",
    "Harness Engineering",
  ],
};
